name: deploy-app
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Flyway Migrations with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/db/migrations:/flyway/sql \
            flyway/flyway:12 \
            -url="${{secrets.DB_URL}}" \
            -user="${{secrets.DB_USER}}" \
            -password="${{secrets.DB_PASSWORD}}" \
            migrate
  check-clojure-cli-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "25"
      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@13.5
        with:
          cli: 1.12.4.1602
          bb: 1.12.215

      # TODO: look at caching clojure tools
      - name: Get Clojure CLI version
        run: clojure --version
      - name: Get babashka version
        run: bb --version
      - name: Run bb ci
        run: bb ci
