name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-clojure-cli-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "25"
      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@13.5
        with:
          cli: 1.12.4.1602
          bb: 1.12.215

      # TODO: look at caching clojure tools
      - name: Get Clojure CLI version
        run: clojure --version
      - name: Get babashka version
        run: bb --version
